name: Test Webhook Listener

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Webhook Server (Test Mode)
        run: node src/server.js &

      - name: Send Test Webhook (Simulate Kibana Alert)
        run: |
          sleep 3
          curl -X POST http://localhost:3000/webhook -H "Content-Type: application/json" -d '{"cpuUsage": 85}'
